name: app_restaurant
version: 1.0.0+1
publish_to: none
description: Skripsi
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.5
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - image/logo.png
  uses-material-design: true

